"""client.is_use_meal_external_id

Revision ID: 0c29545e02df
Revises: 6f24e3ef1c8c
Create Date: 2024-06-13 16:28:11.816762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c29545e02df"
down_revision = "6f24e3ef1c8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("is_use_meal_external_id", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "is_use_meal_external_id")
    # ### end Alembic commands ###
