"""init

Revision ID: 6f24e3ef1c8c
Revises:
Create Date: 2024-04-17 18:30:16.579164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f24e3ef1c8c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_index(op.f("ix_project_title"), "project", ["title"], unique=True)
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("currency_code", sa.String(), nullable=True),
        sa.Column("discount_id", sa.Integer(), nullable=True),
        sa.Column("get_modifier_max_amount", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_use_loyalty", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_split_order_items_for_keeper", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_use_modifier_external_id", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_use_discounts_as_variable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_use_global_modifier_complex", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_skip_update_order_payment_status", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_use_minus_for_discount_amount", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], name=op.f("fk_client_project_id_project")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint("api_key", name=op.f("uq_client_api_key")),
        sa.UniqueConstraint("client_id", name=op.f("uq_client_client_id")),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_category_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
    )
    op.create_table(
        "discount",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("starter_id", sa.String(), nullable=False),
        sa.Column("pos_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_discount_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discount")),
    )
    op.create_table(
        "meal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_meal_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal")),
    )
    op.create_table(
        "modifier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("min_amount", sa.Integer(), nullable=True),
        sa.Column("max_amount", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_modifier_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifier")),
    )
    op.create_table(
        "modifier_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("min_amount", sa.Integer(), nullable=True),
        sa.Column("max_amount", sa.Integer(), nullable=True),
        sa.Column("modifier_external_ids", sa.String(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_modifier_group_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifier_group")),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("starter_id", sa.String(), nullable=False),
        sa.Column("bonuses", sa.Float(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("done", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("discount_price", sa.Float(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_order_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
    )
    op.create_table(
        "shop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], name=op.f("fk_shop_client_id_client")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop")),
    )
    op.create_table(
        "meal_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meal_id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["meal_id"], ["meal.id"], name=op.f("fk_meal_offer_meal_id_meal")),
        sa.ForeignKeyConstraint(["shop_id"], ["shop.id"], name=op.f("fk_meal_offer_shop_id_shop")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_offer")),
    )
    op.create_table(
        "modifier_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modifier_id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.String(), nullable=False),
        sa.Column("starter_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["modifier_id"], ["modifier.id"], name=op.f("fk_modifier_offer_modifier_id_modifier")),
        sa.ForeignKeyConstraint(["shop_id"], ["shop.id"], name=op.f("fk_modifier_offer_shop_id_shop")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifier_offer")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("modifier_offer")
    op.drop_table("meal_offer")
    op.drop_table("shop")
    op.drop_table("order")
    op.drop_table("modifier_group")
    op.drop_table("modifier")
    op.drop_table("meal")
    op.drop_table("discount")
    op.drop_table("category")
    op.drop_table("client")
    op.drop_index(op.f("ix_project_title"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
